// Everything the app shows about a grammar topic besides its questions:
// title, one-line hint, category (colour), a short "glyph" for its tile, and a mini lesson.
// The order of the keys is the order a learner meets the topics in.
// t: title · h: hint · c: category · g: glyph · p: rule points · x: [French example, English]

export const CATEGORIES = {
  verbs: 'Verbs & tenses',
  nouns: 'Nouns & adjectives',
  pronouns: 'Pronouns',
  sentence: 'Building sentences',
  linking: 'Linking & style'
};

export const TOPICS = {
  // ------------------------------------------------------------------ A1
  etre_avoir: { t: 'Être & avoir', h: 'je suis, j’ai, il y a', c: 'verbs', g: 'suis',
    p: ['Être: je suis, tu es, il est, nous sommes, vous êtes, ils sont.', 'Avoir: j’ai, tu as, il a, nous avons, vous avez, ils ont.', 'French uses avoir for age and feelings: avoir 20 ans, avoir faim, soif, froid, peur.', 'Il y a = there is / there are.'],
    x: [['Je suis étudiant.', 'I am a student.'], ['J’ai vingt ans.', 'I am twenty.'], ['Il y a un parc ici.', 'There is a park here.']] },
  er_verbs: { t: 'Regular -er verbs', h: 'je parle, nous parlons, ils parlent', c: 'verbs', g: '-er',
    p: ['Drop -er and add -e, -es, -e, -ons, -ez, -ent.', 'The endings -e, -es, -ent are silent.', 'Spelling: nous mangeons, nous commençons; j’achète, j’appelle, je paie.'],
    x: [['Je parle français.', 'I speak French.'], ['Nous habitons à Paris.', 'We live in Paris.'], ['Ils jouent au foot.', 'They play football.']] },
  basic_articles: { t: 'Le, la, un, une', h: 'le / la / l’ / les · un / une / des', c: 'nouns', g: 'un',
    p: ['Le (masc.), la (fem.), l’ (before a vowel), les (plural) = the.', 'Un (masc.), une (fem.), des (plural) = a / some.', 'Likes and dislikes take le, la, les: j’aime le café.'],
    x: [['J’ai un chat. Le chat dort.', 'I have a cat. The cat is sleeping.'], ['J’adore la musique.', 'I love music.']] },
  possessives: { t: 'My, your, his', h: 'mon, ma, mes · son, sa, ses · leur', c: 'nouns', g: 'mon',
    p: ['The word agrees with the thing owned, not the owner: son frère, sa sœur.', 'Mon, ton, son before a feminine noun starting with a vowel: mon amie.', 'Notre, votre, leur (singular) · nos, vos, leurs (plural).'],
    x: [['C’est ma sœur.', 'This is my sister.'], ['Paul aime sa mère.', 'Paul loves his mother.'], ['Ils vendent leur maison.', 'They are selling their house.']] },
  demonstratives: { t: 'This & that', h: 'ce, cet, cette, ces', c: 'nouns', g: 'ce',
    p: ['Ce + masculine noun, cet + masculine noun starting with a vowel or silent h.', 'Cette + every feminine noun. Ces + every plural noun.'],
    x: [['Ce livre, cet homme', 'This book, this man'], ['Cette maison, ces enfants', 'This house, these children']] },
  questions: { t: 'Asking questions', h: 'où, quand, comment, quel, est-ce que', c: 'sentence', g: '?',
    p: ['Est-ce que + statement = yes / no question.', 'Où (where), quand (when), comment (how), pourquoi (why), combien (how much), qui (who).', 'Qu’est-ce que = what. Quel, quelle, quels, quelles = which / what + noun.'],
    x: [['Est-ce que tu viens ?', 'Are you coming?'], ['Qu’est-ce que tu fais ?', 'What are you doing?'], ['Quelle heure est-il ?', 'What time is it?']] },
  contractions: { t: 'Au, du, aux, des', h: 'à + le = au · de + le = du', c: 'sentence', g: 'au',
    p: ['à + le = au · à + les = aux · à la and à l’ do not change.', 'de + le = du · de + les = des · de la and de l’ do not change.', 'Jouer à + sport, jouer de + instrument.'],
    x: [['Je vais au cinéma.', 'I’m going to the cinema.'], ['Le livre du professeur', 'The teacher’s book'], ['Elle joue du piano.', 'She plays the piano.']] },
  common_irregulars: { t: 'Key irregular verbs', h: 'aller, faire, venir, pouvoir, vouloir', c: 'verbs', g: 'va',
    p: ['Aller: vais, vas, va, allons, allez, vont.', 'Faire: fais, fais, fait, faisons, faites, font.', 'Pouvoir: peux, peux, peut, pouvons, pouvez, peuvent. Vouloir: veux, veux, veut, voulons, voulez, veulent.', 'Venir: viens, viens, vient, venons, venez, viennent.'],
    x: [['Vous faites quoi ?', 'What are you doing?'], ['Ils vont à l’école.', 'They go to school.'], ['Je peux t’aider.', 'I can help you.']] },
  cest_il_est: { t: 'C’est or il est', h: 'c’est un ami · il est gentil', c: 'sentence', g: 'c’',
    p: ['C’est + noun with an article: c’est un médecin.', 'Il est / elle est + adjective or a job with no article: il est médecin.', 'C’est + adjective for a general reaction: c’est super !'],
    x: [['C’est mon frère. Il est grand.', 'This is my brother. He is tall.'], ['Elle est avocate.', 'She is a lawyer.']] },
  position_prepositions: { t: 'Where & when', h: 'sur, sous, dans, chez, à côté de', c: 'sentence', g: 'sur',
    p: ['Sur (on), sous (under), dans (in), devant (in front of), derrière (behind), entre (between).', 'Chez + person = at their place.', 'À + clock time, en + month / year / season (but au printemps).'],
    x: [['Les clés sont dans mon sac.', 'The keys are in my bag.'], ['Je dîne chez Léa.', 'I’m having dinner at Léa’s.'], ['En été, à huit heures', 'In summer, at eight']] },

  // ------------------------------------------------------------------ A2
  present: { t: 'Present tense', h: 'Everyday verbs: je finis, tu prends, ils font', c: 'verbs', g: 'ils',
    p: ['-ir verbs: finis, finis, finit, finissons, finissez, finissent.', '-re verbs: attends, attends, attend, attendons, attendez, attendent.', 'Watch vous dites, vous faites, nous buvons.'],
    x: [['Nous finissons à 18 h.', 'We finish at 6 pm.'], ['Elle prend le bus.', 'She takes the bus.']] },
  articles: { t: 'Some & any', h: 'du, de la, de l’, des · pas de', c: 'nouns', g: 'du',
    p: ['Du, de la, de l’ for an amount you cannot count: du pain, de l’eau.', 'After a negative, they become de: je ne mange pas de viande.', 'After a quantity, de alone: beaucoup de travail, un kilo de pommes.'],
    x: [['Je bois du café.', 'I drink coffee.'], ['Il n’y a plus de lait.', 'There’s no milk left.']] },
  adjective_agreement: { t: 'Adjective agreement', h: 'petit → petite · beau → belle', c: 'nouns', g: '-e',
    p: ['Add -e for feminine, -s for plural: petit, petite, petits, petites.', 'Irregular: beau / bel / belle, vieux / vieil / vieille, blanc / blanche, heureux / heureuse.', 'Most adjectives follow the noun; short common ones (beau, bon, grand, petit) go before.'],
    x: [['Une petite maison blanche', 'A small white house'], ['Un bel appartement', 'A beautiful flat']] },
  negation: { t: 'Negation', h: 'ne … pas, jamais, plus, rien, personne', c: 'sentence', g: 'ne',
    p: ['Ne + verb + pas. Ne becomes n’ before a vowel.', 'Ne … jamais (never), plus (no longer), rien (nothing), personne (nobody), que (only).', 'In the passé composé: je n’ai rien vu, but je n’ai vu personne.'],
    x: [['Je ne fume plus.', 'I don’t smoke any more.'], ['Il n’y a personne.', 'There’s nobody.']] },
  place_prepositions: { t: 'Cities & countries', h: 'à Paris, en France, au Canada, aux États-Unis', c: 'sentence', g: 'en',
    p: ['À + city. En + feminine country (most end in -e). Au + masculine country. Aux + plural.', 'Coming from: de Paris, de France, du Canada, des États-Unis.'],
    x: [['J’habite au Canada.', 'I live in Canada.'], ['Elle vient d’Italie.', 'She comes from Italy.']] },
  futur_proche: { t: 'Futur proche', h: 'aller + infinitive: je vais partir', c: 'verbs', g: 'vais',
    p: ['Aller in the present + infinitive = going to.', 'Negative: je ne vais pas partir.', 'Pronouns go before the infinitive: je vais le faire, je vais me lever.'],
    x: [['Il va pleuvoir.', 'It’s going to rain.'], ['Je ne vais pas sortir.', 'I’m not going to go out.']] },
  passe_compose: { t: 'Passé composé', h: 'j’ai parlé · je suis allé(e)', c: 'verbs', g: 'ai',
    p: ['Avoir or être in the present + past participle.', 'Être with verbs of movement (aller, venir, partir, arriver…) and all reflexive verbs; the participle then agrees with the subject.', 'Irregular participles: fait, pris, vu, eu, été, dit, mis.'],
    x: [['J’ai mangé une pizza.', 'I ate a pizza.'], ['Elle est partie à 8 h.', 'She left at 8.']] },
  object_pronouns: { t: 'Object pronouns', h: 'le, la, les · lui, leur · me, te', c: 'pronouns', g: 'le',
    p: ['Le, la, l’, les replace a direct object.', 'Lui, leur replace à + person.', 'The pronoun goes before the verb: je le vois, je lui parle, je ne le vois pas.'],
    x: [['Tu connais Paul ? — Oui, je le connais.', 'Do you know Paul? — Yes, I know him.'], ['Je lui téléphone.', 'I’m calling him / her.']] },
  reflexive_verbs: { t: 'Reflexive verbs', h: 'je me lève, tu te couches', c: 'verbs', g: 'se',
    p: ['Me, te, se, nous, vous, se before the verb.', 'Negative: je ne me lève pas. Passé composé with être: je me suis levé(e).', 'Commands: lève-toi ! · ne te lève pas !'],
    x: [['Je me lève à 7 h.', 'I get up at 7.'], ['Ils se sont mariés.', 'They got married.']] },
  imperatif: { t: 'Commands', h: 'Parle ! · Allons-y ! · Ne bougez pas !', c: 'verbs', g: '!',
    p: ['Use the tu, nous, vous forms without the subject. -er verbs drop the s of tu: parle !', 'Irregular: sois, soyons, soyez · aie, ayons, ayez.', 'Pronouns go after with a hyphen: regarde-le, donne-moi. In the negative they go before: ne le regarde pas.'],
    x: [['Viens ici !', 'Come here!'], ['Ne t’inquiète pas.', 'Don’t worry.']] },
  comparatives: { t: 'Comparing', h: 'plus … que, moins, aussi · meilleur, mieux', c: 'nouns', g: '>',
    p: ['Plus / moins / aussi + adjective + que.', 'Plus de / moins de / autant de + noun.', 'Bon → meilleur, bien → mieux.', 'Superlative: le plus grand de la classe.'],
    x: [['Elle est plus grande que moi.', 'She is taller than me.'], ['C’est le meilleur film de l’année.', 'It’s the best film of the year.']] },
  imparfait: { t: 'Imparfait', h: 'j’étais, il faisait, nous allions', c: 'verbs', g: '-ais',
    p: ['Stem of the present nous form + -ais, -ais, -ait, -ions, -iez, -aient.', 'Only être is irregular: j’étais.', 'Used for habits, descriptions and background in the past.'],
    x: [['Quand j’étais petit, je jouais au foot.', 'When I was little, I used to play football.'], ['Il faisait froid.', 'It was cold.']] },
  passe_recent: { t: 'Just done & doing now', h: 'venir de · être en train de', c: 'verbs', g: 'de',
    p: ['Venir de + infinitive = to have just done.', 'Être en train de + infinitive = to be in the middle of doing.', 'In a past story: il venait de partir, j’étais en train de lire.'],
    x: [['Je viens de manger.', 'I’ve just eaten.'], ['Elle est en train de dormir.', 'She’s sleeping right now.']] },

  // ------------------------------------------------------------------ B1
  imparfait_vs_passe_compose: { t: 'Imparfait vs passé composé', h: 'Background vs events', c: 'verbs', g: 'vs',
    p: ['Passé composé: completed events, one after another, or with a stated duration.', 'Imparfait: background, descriptions, habits, an action in progress.', 'Typical: je dormais quand le téléphone a sonné.'],
    x: [['Il pleuvait quand je suis sorti.', 'It was raining when I went out.'], ['J’ai habité à Lyon pendant deux ans.', 'I lived in Lyon for two years.']] },
  futur_simple: { t: 'Futur simple', h: 'je parlerai, tu seras, il ira', c: 'verbs', g: '-rai',
    p: ['Infinitive + -ai, -as, -a, -ons, -ez, -ont.', 'Irregular stems: ser-, aur-, ir-, fer-, viendr-, verr-, pourr-, voudr-, devr-, saur-.', 'After quand and dès que, use the future. After si, use the present.'],
    x: [['Je t’appellerai demain.', 'I’ll call you tomorrow.'], ['Quand tu arriveras, nous dînerons.', 'When you arrive, we’ll have dinner.']] },
  conditionnel_present: { t: 'Conditionnel présent', h: 'je voudrais, tu devrais, on pourrait', c: 'verbs', g: '-rais',
    p: ['Future stem + imparfait endings: -ais, -ais, -ait, -ions, -iez, -aient.', 'Politeness (je voudrais), advice (tu devrais), wishes (j’aimerais).', 'Result of si + imparfait: si j’avais le temps, je viendrais.'],
    x: [['Je voudrais un café.', 'I’d like a coffee.'], ['Tu devrais te reposer.', 'You should rest.']] },
  plus_que_parfait: { t: 'Plus-que-parfait', h: 'j’avais parlé, elle était partie', c: 'verbs', g: 'avais',
    p: ['Imparfait of avoir or être + past participle.', 'It marks an action that happened before another past action.', 'Si seulement + plus-que-parfait expresses regret.'],
    x: [['Elle était déjà partie quand je suis arrivé.', 'She had already left when I arrived.'], ['Si seulement j’avais su !', 'If only I had known!']] },
  pronoun_y: { t: 'The pronoun y', h: 'j’y vais, j’y pense', c: 'pronouns', g: 'y',
    p: ['Y replaces a place: j’y vais.', 'Y replaces à + thing: j’y pense. For people use lui / leur or à elle.', 'Position: before the verb; vas-y in commands.'],
    x: [['Tu vas à Paris ? — Oui, j’y vais.', 'Are you going to Paris? — Yes, I’m going there.'], ['Je n’y pense plus.', 'I don’t think about it any more.']] },
  pronoun_en: { t: 'The pronoun en', h: 'j’en veux, j’en ai deux', c: 'pronouns', g: 'en',
    p: ['En replaces du / de la / des + noun: j’en veux.', 'With a quantity, keep the number: j’en ai deux.', 'En replaces de + thing: j’en parle, j’en ai besoin.'],
    x: [['Tu veux du café ? — Oui, j’en veux.', 'Do you want some coffee? — Yes, I do.'], ['Il en a trois.', 'He has three (of them).']] },
  relative_pronouns: { t: 'Qui, que, où, dont', h: 'l’ami qui… · le film que… · le livre dont…', c: 'pronouns', g: 'qui',
    p: ['Qui = subject (a verb follows). Que = object (a subject follows).', 'Où = place or time. Dont = de + noun (parler de, avoir besoin de).', 'Ce qui / ce que / ce dont = what.'],
    x: [['Le film que j’ai vu', 'The film I saw'], ['Le livre dont je parle', 'The book I’m talking about']] },
  subjonctif_present: { t: 'Subjonctif présent', h: 'il faut que je fasse', c: 'verbs', g: 'que',
    p: ['Stem of ils (present) + -e, -es, -e, -ions, -iez, -ent.', 'After necessity, wishes, emotions and doubt: il faut que, je veux que, j’ai peur que.', 'Irregular: sois, aie, aille, fasse, puisse, sache, veuille.'],
    x: [['Il faut que tu viennes.', 'You have to come.'], ['Je suis content que tu sois là.', 'I’m glad you’re here.']] },
  si_clauses: { t: 'Si clauses', h: 'si + présent → futur · si + imparfait → conditionnel', c: 'linking', g: 'si',
    p: ['Likely: si + present, result in the future. Si tu viens, je serai content.', 'Imagined: si + imparfait, result in the conditional. Si j’avais le temps, je viendrais.', 'Never use the future or conditional right after si.'],
    x: [['S’il pleut, nous resterons ici.', 'If it rains, we’ll stay here.'], ['Si j’étais riche, je voyagerais.', 'If I were rich, I’d travel.']] },
  gerondif: { t: 'Gérondif', h: 'en parlant, en faisant', c: 'verbs', g: '-ant',
    p: ['En + stem of the nous form + -ant: en mangeant, en finissant.', 'Irregular: étant, ayant, sachant.', 'It means while, by or when doing, with the same subject as the main verb.'],
    x: [['Il travaille en écoutant de la musique.', 'He works while listening to music.'], ['J’ai appris en pratiquant.', 'I learned by practising.']] },
  pp_agreement: { t: 'Past participle agreement', h: 'elle est partie · je les ai vus', c: 'verbs', g: '-é(e)s',
    p: ['With être: agrees with the subject.', 'With avoir: agrees only with a direct object placed before the verb (la, les, que).', 'Never agrees with en, lui or leur. Reflexive: elle s’est lavée, but elle s’est lavé les mains.'],
    x: [['Les photos que j’ai prises', 'The photos I took'], ['Elles se sont parlé.', 'They talked to each other.']] },
  time_expressions: { t: 'Time expressions', h: 'depuis, pendant, il y a, dans, en', c: 'sentence', g: 'il y a',
    p: ['Depuis + present: still going on. Pendant: a finished length of time.', 'Il y a = ago. Dans = in (from now). En = time needed.', 'Ça fait deux ans que… = depuis deux ans.'],
    x: [['J’habite ici depuis deux ans.', 'I’ve lived here for two years.'], ['Je suis arrivé il y a deux ans.', 'I arrived two years ago.']] },
  celui_le_mien: { t: 'Celui & le mien', h: 'celui-ci, celle de Paul · le mien, la tienne', c: 'pronouns', g: 'mien',
    p: ['Celui, celle, ceux, celles = the one(s), followed by -ci / -là, de, or qui / que.', 'Le mien, la mienne, les miens, les miennes = mine; le tien, le sien, le nôtre, le vôtre, le leur.', 'They agree with the thing they replace.'],
    x: [['Ma voiture et celle de Paul', 'My car and Paul’s'], ['C’est le tien ?', 'Is this yours?']] },

  // ------------------------------------------------------------------ B2
  double_object_pronouns: { t: 'Double pronouns', h: 'je le lui donne, il m’en parle', c: 'pronouns', g: 'le lui',
    p: ['Order: me / te / se / nous / vous → le / la / les → lui / leur → y → en.', 'Commands: donne-le-moi, donne-m’en.', 'Both pronouns go before the auxiliary or the infinitive.'],
    x: [['Je le lui ai dit.', 'I told him (it).'], ['Il m’en a parlé.', 'He told me about it.']] },
  compound_relative_pronouns: { t: 'Lequel, auquel, duquel', h: 'Relative pronouns after prepositions', c: 'pronouns', g: 'lequel',
    p: ['Preposition + lequel / laquelle / lesquels / lesquelles for things.', 'à + lequel = auquel; de + lequel = duquel (after près de, à côté de…).', 'For people, preposition + qui is usual: l’ami avec qui je voyage.'],
    x: [['La raison pour laquelle je pars', 'The reason why I’m leaving'], ['Le projet auquel je participe', 'The project I’m taking part in']] },
  conditionnel_passe: { t: 'Conditionnel passé', h: 'j’aurais dû, elle serait venue', c: 'verbs', g: 'aurais',
    p: ['Conditional of avoir or être + past participle.', 'Regret and reproach: j’aurais dû, tu aurais pu.', 'Result of si + plus-que-parfait: si j’avais su, je serais venu.'],
    x: [['J’aurais dû t’appeler.', 'I should have called you.'], ['Si tu avais demandé, je t’aurais aidé.', 'If you had asked, I would have helped you.']] },
  connectors: { t: 'Connectors', h: 'bien que, malgré, puisque, pourtant, donc', c: 'linking', g: 'donc',
    p: ['Cause: parce que, puisque, comme, grâce à, à cause de.', 'Consequence: donc, c’est pourquoi, si bien que.', 'Concession: bien que + subjunctive, malgré + noun, pourtant, quand même.', 'Purpose: pour que + subjunctive, afin de + infinitive.'],
    x: [['Bien qu’il soit fatigué, il travaille.', 'Although he is tired, he is working.'], ['Grâce à toi, j’ai réussi.', 'Thanks to you, I succeeded.']] },
  passive: { t: 'Passive voice', h: 'la maison a été construite en 1900', c: 'verbs', g: 'été',
    p: ['Être (in any tense) + past participle, which agrees with the subject.', 'The agent is introduced by par (sometimes de).', 'French often prefers on or a reflexive: on parle français, ça se dit.'],
    x: [['Le voleur a été arrêté par la police.', 'The thief was arrested by the police.'], ['Ce vin se boit frais.', 'This wine is drunk chilled.']] },
  reported_speech: { t: 'Reported speech', h: 'il a dit que… · elle m’a demandé si…', c: 'linking', g: '« »',
    p: ['Statement: que. Yes / no question: si. What: ce que / ce qui. Command: de + infinitive.', 'After a past reporting verb: present → imparfait, passé composé → plus-que-parfait, future → conditional.', 'Time words shift: demain → le lendemain, hier → la veille.'],
    x: [['Il a dit qu’il était fatigué.', 'He said he was tired.'], ['Elle m’a demandé si je venais.', 'She asked me if I was coming.']] },
  subjonctif_vs_indicatif: { t: 'Subjunctive or indicative', h: 'je pense qu’il a · je ne pense pas qu’il ait', c: 'verbs', g: 'ait',
    p: ['Certainty and opinion → indicative: je pense que, il est clair que, j’espère que.', 'Doubt, feeling, will, necessity → subjunctive.', 'Bien que, pour que, avant que → subjunctive. Parce que, après que, pendant que → indicative.'],
    x: [['Je crois qu’il a raison.', 'I think he’s right.'], ['Je ne crois pas qu’il ait raison.', 'I don’t think he’s right.']] },
  subjonctif_passe: { t: 'Subjonctif passé', h: 'que j’aie fini, qu’elle soit partie', c: 'verbs', g: 'aie',
    p: ['Subjunctive of avoir or être + past participle.', 'Used when the action is already finished at the time of the main verb.', 'Same subject → infinitif passé: je suis content d’avoir réussi.'],
    x: [['Je suis content que tu sois venu.', 'I’m glad you came.'], ['Bien qu’il ait plu, nous sommes sortis.', 'Although it rained, we went out.']] },
  futur_anterieur: { t: 'Futur antérieur', h: 'j’aurai fini, elle sera partie', c: 'verbs', g: 'aurai',
    p: ['Future of avoir or être + past participle.', 'An action finished before another future moment: quand j’aurai fini, je sortirai.', 'It can also be a guess about the past: il aura oublié.'],
    x: [['Dans une heure, j’aurai fini.', 'In an hour I’ll have finished.'], ['Dès qu’elle sera arrivée, nous partirons.', 'As soon as she has arrived, we’ll leave.']] },
  verb_prepositions: { t: 'Verb + à or de', h: 'commencer à, décider de, aimer faire', c: 'sentence', g: 'à / de',
    p: ['No preposition: aimer, vouloir, pouvoir, devoir, savoir, espérer + infinitive.', 'À: commencer à, apprendre à, réussir à, aider à, penser à.', 'De: décider de, essayer de, oublier de, arrêter de, avoir envie de.', 'Dire / demander à quelqu’un de faire.'],
    x: [['J’ai décidé de partir.', 'I decided to leave.'], ['Elle apprend à conduire.', 'She is learning to drive.']] },
  infinitif_passe: { t: 'Infinitif passé', h: 'après avoir mangé, merci d’être venu', c: 'verbs', g: 'avoir',
    p: ['Avoir or être + past participle: avoir fini, être parti(e).', 'Always after après: après avoir dîné. Avant de takes a simple infinitive.', 'Negative: ne pas avoir appelé. Pronouns before the auxiliary: après l’avoir vu.'],
    x: [['Après être rentrée, elle a dîné.', 'After getting home, she had dinner.'], ['Merci d’être venu.', 'Thanks for coming.']] },

  // ------------------------------------------------------------------ C1
  passe_simple: { t: 'Passé simple', h: 'il fut, ils eurent, elle vint', c: 'verbs', g: 'fut',
    p: ['A written, literary past: it replaces the passé composé in novels and history.', '-er verbs: -ai, -as, -a, -âmes, -âtes, -èrent. Others: -is… or -us…', 'Key forms: il fut (être), il eut (avoir), il fit (faire), il vint (venir), il vit (voir).'],
    x: [['Il ouvrit la porte et sortit.', 'He opened the door and went out.'], ['Ils vécurent heureux.', 'They lived happily.']] },
  fine_negation: { t: 'Fine points of negation', h: 'ne explétif, ne … guère, ni … ni, aucun', c: 'sentence', g: 'ni',
    p: ['Ne explétif has no negative meaning: avant qu’il ne parte, je crains qu’il ne vienne.', 'Ne … guère (hardly), ne … point (literary pas), ne … nullement (not at all).', 'Ni … ni and aucun are used without pas. Negatives combine: plus jamais, plus rien.'],
    x: [['Il n’a ni frère ni sœur.', 'He has neither brother nor sister.'], ['Partons avant qu’il ne pleuve.', 'Let’s leave before it rains.']] },
  mise_en_relief: { t: 'Emphasis', h: 'c’est … qui / que · ce qui …, c’est …', c: 'linking', g: 'c’est',
    p: ['C’est … qui for the subject, c’est … que for everything else.', 'Ce qui / ce que / ce dont / ce à quoi …, c’est … puts the key element at the end.', 'A noun moved to the front is picked up by a pronoun: ce film, je l’ai adoré.'],
    x: [['C’est moi qui ai raison.', 'I’m the one who’s right.'], ['Ce dont j’ai besoin, c’est de repos.', 'What I need is rest.']] },
  advanced_connectors: { t: 'Advanced connectors', h: 'quoi que, avoir beau, or, néanmoins, quitte à', c: 'linking', g: 'or',
    p: ['Quoi que (whatever) vs quoique (although), both + subjunctive.', 'Avoir beau + infinitive = in vain. Quitte à = even if it means.', 'Or introduces a twist; néanmoins, toutefois = however; d’où + noun = hence.', 'Faute de (for lack of), à force de (by dint of).'],
    x: [['Quoi que tu dises, je reste.', 'Whatever you say, I’m staying.'], ['J’ai beau essayer, je n’y arrive pas.', 'However hard I try, I can’t do it.']] },
  participe_present: { t: 'Participe présent', h: 'ayant fini · fatigant vs fatiguant', c: 'verbs', g: 'ayant',
    p: ['The participle is a verb form and never agrees: les élèves ayant fini.', 'The verbal adjective agrees: des enfants obéissants.', 'Spelling pairs: fatiguant / fatigant, convainquant / convaincant, négligeant / négligent.', 'Compound form for an earlier action: ayant fini, étant arrivée.'],
    x: [['Étant malade, il est resté chez lui.', 'Being ill, he stayed home.'], ['C’est un travail fatigant.', 'It’s tiring work.']] },
  nominalisation: { t: 'Nominalisation', h: 'augmenter → l’augmentation', c: 'nouns', g: '-tion',
    p: ['Verb → noun: -tion / -sion (f.), -ment (m.), -age (m.), -ure (f.), or no suffix (le départ, la vente).', 'Adjective → noun: -té, -esse, -eur, -ie, -ance, -itude.', 'The clause connector changes too: parce que → en raison de, bien que → malgré.'],
    x: [['Les prix ont augmenté. → l’augmentation des prix', 'Prices rose. → the rise in prices'], ['Malgré sa fatigue, il continue.', 'Despite his tiredness, he carries on.']] },
  tricky_agreements: { t: 'Tricky agreements', h: 'tout, même, demi, cent, couleurs', c: 'nouns', g: 'tout',
    p: ['Tout (very) is invariable except before a feminine consonant: tout étonnée, toute petite.', 'Compound and noun colours never change: des yeux bleu clair, des chaussures marron.', 'Quatre-vingts but quatre-vingt-trois; deux cents but deux cent dix; mille never changes.', 'Past participle + infinitive: les enfants que j’ai vus jouer, la robe qu’elle a fait faire.'],
    x: [['Une heure et demie, une demi-heure', 'An hour and a half, half an hour'], ['Ils se sont succédé.', 'They followed one another.']] },
  condition_nuance: { t: 'Conditions & hypotheses', h: 'au cas où, à moins que, comme si, pourvu que', c: 'linking', g: 'cas',
    p: ['Au cas où + conditional. À condition que, pourvu que, à moins que + subjunctive.', 'Si + plus-que-parfait → conditionnel passé (or present for a result now).', 'Comme si + imparfait or plus-que-parfait. Même si + indicative.', 'Si … et que + subjunctive for a second condition.'],
    x: [['Au cas où il pleuvrait, prends un parapluie.', 'In case it rains, take an umbrella.'], ['Il parle comme s’il savait tout.', 'He talks as if he knew everything.']] }
};
